// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMCOgfeCzmxpWuoBts0E6Zb25SBbwWz0',
    appId: '1:900899630281:web:329035203ae0c9cb00f118',
    messagingSenderId: '900899630281',
    projectId: 'the-guild-fc0de',
    authDomain: 'the-guild-fc0de.firebaseapp.com',
    storageBucket: 'the-guild-fc0de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0KmCKXP60WSGtFD3Jq176xFGwQUEdZiY',
    appId: '1:900899630281:android:09d58910f7b8abb800f118',
    messagingSenderId: '900899630281',
    projectId: 'the-guild-fc0de',
    storageBucket: 'the-guild-fc0de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChcb6To269iUctBSkM4ulGW2sC1jsmK1c',
    appId: '1:900899630281:ios:220c7c383a34f70d00f118',
    messagingSenderId: '900899630281',
    projectId: 'the-guild-fc0de',
    storageBucket: 'the-guild-fc0de.firebasestorage.app',
    iosClientId: '900899630281-016h4f8kru0tafh21rkffdrmjm6fvj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.theGuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChcb6To269iUctBSkM4ulGW2sC1jsmK1c',
    appId: '1:900899630281:ios:220c7c383a34f70d00f118',
    messagingSenderId: '900899630281',
    projectId: 'the-guild-fc0de',
    storageBucket: 'the-guild-fc0de.firebasestorage.app',
    iosClientId: '900899630281-016h4f8kru0tafh21rkffdrmjm6fvj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.theGuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMCOgfeCzmxpWuoBts0E6Zb25SBbwWz0',
    appId: '1:900899630281:web:18f755e0fb257c5600f118',
    messagingSenderId: '900899630281',
    projectId: 'the-guild-fc0de',
    authDomain: 'the-guild-fc0de.firebaseapp.com',
    storageBucket: 'the-guild-fc0de.firebasestorage.app',
  );
}